version: 2.1
jobs:
  build:  
    docker:
      - image: node:latest
    environment:
      process.env.CI: "false"
    steps:
      - checkout
      - run:
          name: Install deps
          command: npm ci
      - run:
          name: Run build
          command: npm run build

workflows:
  sample: 
    jobs:
      - build
